# Generated by Django 5.2.5 on 2026-04-14 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nivel', models.IntegerField()),
                ('grupo', models.IntegerField()),
                ('subgrupo', models.CharField(max_length=10)),
                ('horario', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno'), ('Diurno_Nocturno', 'Diurno_Nocturno')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('desactivo', 'Desactivo')], default='activo', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('puesto', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=10)),
                ('horario', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno'), ('Diurno_Nocturno', 'Diurno_Nocturno')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('desactivo', 'Desactivo')], default='activo', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
