# Generated by Django 5.2.5 on 2026-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_estudiante_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='apellido1',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='apellido2',
        ),
        migrations.AddField(
            model_name='personal',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='personal',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Docente', 'Docente'), ('Administrativo', 'Administrativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='horario',
            field=models.CharField(blank=True, choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno'), ('Diurno_Nocturno', 'Diurno_Nocturno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='puesto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='titulo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
