# Generated by Django 5.2.5 on 2026-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_personal_apellido1_remove_personal_apellido2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='personal',
            name='puesto',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Administrativo', 'Administrativo')], max_length=100),
        ),
    ]
