# Generated by Django 5.2.5 on 2026-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_personal_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
