# Generated by Django 5.2.5 on 2026-04-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_personal_departamento_alter_personal_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
