# Generated by Django 5.2.5 on 2026-04-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_estudiante_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='subgrupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10),
        ),
    ]
