# Generated by Django 5.1.7 on 2026-04-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_estudiante_grupo_alter_estudiante_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='apellido',
        ),
        migrations.AddField(
            model_name='personal',
            name='apellido1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personal',
            name='apellido2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
