# Generated by Django 5.1.7 on 2026-04-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(help_text='Identificación de la persona (Docente, Administrativo o Estudiante)', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de la marca')),
                ('tipo_persona', models.CharField(blank=True, choices=[('personal', 'Personal'), ('estudiante', 'Estudiante')], help_text='Tipo de persona (se determina automáticamente al registrar)', max_length=10)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
